import type { Patient, Diagnosis, Report, Alert, DashboardStats, ChartData, TimelineEvent } from "./types"

export const mockPatients: Patient[] = [
  {
    id: "P-1001",
    name: "John Doe",
    age: 45,
    gender: "male",
    lastVisit: "2024-01-15",
    condition: "Hypertension",
    riskLevel: "high",
    bloodPressure: "145/95",
    heartRate: 88,
    temperature: 98.6,
    weight: 82,
    height: 175,
    bloodType: "O+",
    phone: "+1 555-0101",
    email: "john.doe@email.com",
    medications: [
      { id: "M1", name: "Lisinopril", dosage: "10mg", frequency: "Once daily", startDate: "2023-06-01" },
      { id: "M2", name: "Amlodipine", dosage: "5mg", frequency: "Once daily", startDate: "2023-08-15" },
    ],
  },
  {
    id: "P-1002",
    name: "Sarah Wilson",
    age: 32,
    gender: "female",
    lastVisit: "2024-01-14",
    condition: "Diabetes Type 2",
    riskLevel: "medium",
    bloodPressure: "120/80",
    heartRate: 72,
    temperature: 98.4,
    weight: 68,
    height: 165,
    bloodType: "A+",
    phone: "+1 555-0102",
    email: "sarah.wilson@email.com",
    medications: [
      { id: "M3", name: "Metformin", dosage: "500mg", frequency: "Twice daily", startDate: "2023-03-01" },
    ],
  },
  {
    id: "P-1003",
    name: "Michael Brown",
    age: 58,
    gender: "male",
    lastVisit: "2024-01-13",
    condition: "Cardiac Arrhythmia",
    riskLevel: "critical",
    bloodPressure: "160/100",
    heartRate: 110,
    temperature: 99.1,
    weight: 95,
    height: 180,
    bloodType: "B-",
    phone: "+1 555-0103",
    email: "michael.brown@email.com",
    medications: [
      { id: "M4", name: "Amiodarone", dosage: "200mg", frequency: "Once daily", startDate: "2023-11-01" },
      { id: "M5", name: "Warfarin", dosage: "5mg", frequency: "Once daily", startDate: "2023-11-01" },
    ],
  },
  {
    id: "P-1004",
    name: "Emily Chen",
    age: 28,
    gender: "female",
    lastVisit: "2024-01-12",
    condition: "Asthma",
    riskLevel: "low",
    bloodPressure: "115/75",
    heartRate: 68,
    temperature: 98.2,
    weight: 55,
    height: 160,
    bloodType: "AB+",
    phone: "+1 555-0104",
    email: "emily.chen@email.com",
    medications: [
      { id: "M6", name: "Albuterol", dosage: "90mcg", frequency: "As needed", startDate: "2022-01-01" },
    ],
  },
  {
    id: "P-1005",
    name: "Robert Taylor",
    age: 62,
    gender: "male",
    lastVisit: "2024-01-11",
    condition: "COPD",
    riskLevel: "high",
    bloodPressure: "138/88",
    heartRate: 82,
    temperature: 98.8,
    weight: 78,
    height: 172,
    bloodType: "O-",
    phone: "+1 555-0105",
    email: "robert.taylor@email.com",
    medications: [
      { id: "M7", name: "Tiotropium", dosage: "18mcg", frequency: "Once daily", startDate: "2023-02-01" },
      { id: "M8", name: "Fluticasone", dosage: "250mcg", frequency: "Twice daily", startDate: "2023-02-01" },
    ],
  },
  {
    id: "P-1006",
    name: "Amanda Martinez",
    age: 41,
    gender: "female",
    lastVisit: "2024-01-10",
    condition: "Migraine",
    riskLevel: "low",
    bloodPressure: "118/76",
    heartRate: 70,
    temperature: 98.4,
    weight: 62,
    height: 168,
    bloodType: "A-",
    phone: "+1 555-0106",
    email: "amanda.martinez@email.com",
    medications: [
      { id: "M9", name: "Sumatriptan", dosage: "50mg", frequency: "As needed", startDate: "2023-05-01" },
    ],
  },
  {
    id: "P-1007",
    name: "David Lee",
    age: 55,
    gender: "male",
    lastVisit: "2024-01-09",
    condition: "Coronary Artery Disease",
    riskLevel: "critical",
    bloodPressure: "155/98",
    heartRate: 95,
    temperature: 98.9,
    weight: 88,
    height: 178,
    bloodType: "B+",
    phone: "+1 555-0107",
    email: "david.lee@email.com",
    medications: [
      { id: "M10", name: "Atorvastatin", dosage: "40mg", frequency: "Once daily", startDate: "2022-08-01" },
      { id: "M11", name: "Aspirin", dosage: "81mg", frequency: "Once daily", startDate: "2022-08-01" },
      { id: "M12", name: "Metoprolol", dosage: "50mg", frequency: "Twice daily", startDate: "2022-08-01" },
    ],
  },
  {
    id: "P-1008",
    name: "Jennifer Adams",
    age: 36,
    gender: "female",
    lastVisit: "2024-01-08",
    condition: "Hypothyroidism",
    riskLevel: "medium",
    bloodPressure: "122/78",
    heartRate: 65,
    temperature: 97.8,
    weight: 70,
    height: 163,
    bloodType: "O+",
    phone: "+1 555-0108",
    email: "jennifer.adams@email.com",
    medications: [
      { id: "M13", name: "Levothyroxine", dosage: "75mcg", frequency: "Once daily", startDate: "2021-11-01" },
    ],
  },
]

export const mockDiagnoses: Diagnosis[] = [
  {
    id: "D-001",
    patientId: "P-1001",
    disease: "Hypertensive Heart Disease",
    confidence: 92,
    severity: "high",
    date: "2024-01-15",
    aiGenerated: true,
    contributingFactors: ["Elevated blood pressure", "ECG abnormalities", "Age factor"],
  },
  {
    id: "D-002",
    patientId: "P-1003",
    disease: "Atrial Fibrillation",
    confidence: 88,
    severity: "critical",
    date: "2024-01-13",
    aiGenerated: true,
    contributingFactors: ["Irregular heart rhythm", "Elevated heart rate", "ECG patterns"],
  },
  {
    id: "D-003",
    patientId: "P-1007",
    disease: "Coronary Artery Stenosis",
    confidence: 95,
    severity: "critical",
    date: "2024-01-09",
    aiGenerated: true,
    contributingFactors: ["Chest pain symptoms", "ECG ischemic changes", "Risk factors"],
  },
  {
    id: "D-004",
    patientId: "P-1002",
    disease: "Diabetic Retinopathy - Early Stage",
    confidence: 78,
    severity: "medium",
    date: "2024-01-14",
    aiGenerated: true,
    contributingFactors: ["Diabetes history", "Retinal imaging findings"],
  },
  {
    id: "D-005",
    patientId: "P-1005",
    disease: "COPD Exacerbation",
    confidence: 85,
    severity: "high",
    date: "2024-01-11",
    aiGenerated: true,
    contributingFactors: ["Decreased lung function", "Symptom progression", "X-ray findings"],
  },
]

export const mockReports: Report[] = [
  {
    id: "R-001",
    patientId: "P-1001",
    patientName: "John Doe",
    type: "ecg",
    title: "12-Lead ECG Analysis",
    date: "2024-01-15",
    aiAnalyzed: true,
    analysisResult: "Abnormal ECG pattern detected - Left ventricular hypertrophy",
  },
  {
    id: "R-002",
    patientId: "P-1003",
    patientName: "Michael Brown",
    type: "ecg",
    title: "Holter Monitor Report",
    date: "2024-01-13",
    aiAnalyzed: true,
    analysisResult: "Atrial fibrillation episodes detected",
  },
  {
    id: "R-003",
    patientId: "P-1005",
    patientName: "Robert Taylor",
    type: "xray",
    title: "Chest X-Ray",
    date: "2024-01-11",
    aiAnalyzed: true,
    analysisResult: "Hyperinflation consistent with COPD",
  },
  {
    id: "R-004",
    patientId: "P-1007",
    patientName: "David Lee",
    type: "mri",
    title: "Cardiac MRI",
    date: "2024-01-09",
    aiAnalyzed: true,
    analysisResult: "Reduced ejection fraction - 40%",
  },
  {
    id: "R-005",
    patientId: "P-1002",
    patientName: "Sarah Wilson",
    type: "lab",
    title: "HbA1c Test Results",
    date: "2024-01-14",
    aiAnalyzed: false,
    analysisResult: "HbA1c: 7.2% - Moderate glycemic control",
  },
]

export const mockAlerts: Alert[] = [
  {
    id: "A-001",
    type: "critical",
    title: "Critical Vital Signs",
    message: "Blood pressure exceeds safe threshold",
    patientId: "P-1003",
    patientName: "Michael Brown",
    timestamp: "2024-01-15T10:30:00",
    read: false,
  },
  {
    id: "A-002",
    type: "critical",
    title: "Abnormal ECG Detected",
    message: "AI detected potential cardiac arrhythmia",
    patientId: "P-1007",
    patientName: "David Lee",
    timestamp: "2024-01-15T09:15:00",
    read: false,
  },
  {
    id: "A-003",
    type: "warning",
    title: "Low Confidence Diagnosis",
    message: "Review required - confidence below threshold",
    patientId: "P-1002",
    patientName: "Sarah Wilson",
    timestamp: "2024-01-15T08:45:00",
    read: false,
  },
  {
    id: "A-004",
    type: "warning",
    title: "Medication Interaction",
    message: "Potential drug interaction detected",
    patientId: "P-1001",
    patientName: "John Doe",
    timestamp: "2024-01-14T16:20:00",
    read: true,
  },
  {
    id: "A-005",
    type: "info",
    title: "Follow-up Due",
    message: "Scheduled follow-up appointment approaching",
    patientId: "P-1004",
    patientName: "Emily Chen",
    timestamp: "2024-01-14T14:00:00",
    read: true,
  },
]

export const mockDashboardStats: DashboardStats = {
  totalPatients: 1247,
  activeCases: 89,
  criticalAlerts: 12,
  aiDiagnosesToday: 34,
  patientGrowth: 12.5,
  diagnosisAccuracy: 94.2,
}

export const mockPatientGrowthData: ChartData[] = [
  { name: "Jan", value: 1050 },
  { name: "Feb", value: 1080 },
  { name: "Mar", value: 1120 },
  { name: "Apr", value: 1140 },
  { name: "May", value: 1175 },
  { name: "Jun", value: 1190 },
  { name: "Jul", value: 1210 },
  { name: "Aug", value: 1225 },
  { name: "Sep", value: 1240 },
  { name: "Oct", value: 1247 },
]

export const mockDiseaseDistribution: ChartData[] = [
  { name: "Cardiovascular", value: 35 },
  { name: "Respiratory", value: 22 },
  { name: "Diabetes", value: 18 },
  { name: "Neurological", value: 12 },
  { name: "Other", value: 13 },
]

export const mockAIConfidenceData: ChartData[] = [
  { name: "90-100%", value: 45 },
  { name: "80-89%", value: 30 },
  { name: "70-79%", value: 15 },
  { name: "Below 70%", value: 10 },
]

export const mockTimelineEvents: TimelineEvent[] = [
  {
    id: "T-001",
    type: "visit",
    title: "Regular Checkup",
    description: "Routine examination and vitals assessment",
    date: "2024-01-15",
  },
  {
    id: "T-002",
    type: "diagnosis",
    title: "AI Diagnosis: Hypertensive Heart Disease",
    description: "Confidence: 92% - Based on ECG and vital signs analysis",
    date: "2024-01-15",
  },
  {
    id: "T-003",
    type: "report",
    title: "ECG Report Uploaded",
    description: "12-Lead ECG analysis completed",
    date: "2024-01-14",
  },
  {
    id: "T-004",
    type: "medication",
    title: "Medication Adjusted",
    description: "Amlodipine dosage increased to 10mg",
    date: "2024-01-10",
  },
  {
    id: "T-005",
    type: "note",
    title: "Clinical Note Added",
    description: "Patient reports improved symptoms after medication adjustment",
    date: "2024-01-08",
  },
]
